### ISSUE TITLE
Enable Issues in GS1 Version

### ISSUE THREAD

**Issue by Echsecutor** [gs1-germany/checkDigitCalculator#5]
Currently the GS1 Fork does not have an Issues section:

![image](https://github.com/RalphTro/checkDigitCalculator/assets/5765579/f59ce931-0afe-4ddf-834f-9a3ef5d81256)

You might want to enable those. See https://softwareengineering.stackexchange.com/a/179470/293697

**Comment by RalphTro** [comment]
Done - many thanks for making me aware about this, @Echsecutor!
